import type { DemoCase } from "./types";

export const demoCases: DemoCase[] = [
  {
    id: "easy-recovery",
    name: "轻松恢复跑",
    summary: "4km recovery，RPE 2，状态良好",
    payload: {
      distance_km: 4,
      duration_min: 28,
      user_level: "beginner",
      run_type_main: "recovery",
      run_type_modifier: ["completed"],
      run_type: null,
      run_time_period: "evening",
      rpe: 2,
      sleep_hours: 8.2,
      fatigue_level: 2,
      soreness_level: 1,
      avg_hr: null,
      max_hr: null,
      diet_preference: "normal",
      tomorrow_plan: "recovery_easy",
      past_48h_training: "rest",
      symptoms: [],
    },
  },
  {
    id: "sleep-debt-steady",
    name: "睡眠不足稳态跑",
    summary: "9km steady，睡眠 4.8h，夜间完成",
    payload: {
      distance_km: 9,
      duration_min: 55,
      user_level: "regular",
      run_type_main: "steady",
      run_type_modifier: ["hills"],
      run_type: null,
      run_time_period: "night",
      rpe: 6,
      sleep_hours: 4.8,
      fatigue_level: 6,
      soreness_level: 3,
      avg_hr: 148,
      max_hr: null,
      diet_preference: "takeout",
      tomorrow_plan: "strength_cross",
      past_48h_training: "easy_training",
      symptoms: [],
    },
  },
  {
    id: "long-muscle-load",
    name: "长距离肌肉负荷",
    summary: "18km long，RPE 7，酸痛明显",
    payload: {
      distance_km: 18,
      duration_min: 118,
      user_level: "advanced",
      run_type_main: "long",
      run_type_modifier: ["pace_block"],
      run_type: "long",
      run_time_period: "morning",
      rpe: 7,
      sleep_hours: 7.4,
      fatigue_level: 7,
      soreness_level: 8,
      avg_hr: 150,
      max_hr: null,
      diet_preference: "normal",
      tomorrow_plan: "rest",
      past_48h_training: "easy_training",
      symptoms: [],
    },
  },
];
