import type { DemoCase } from "./types";

export const demoCases: DemoCase[] = [
  {
    id: "easy-recovery",
    name: "轻松恢复",
    summary: "5km easy，RPE 3，睡眠充足",
    payload: {
      distance_km: 5,
      duration_min: 32,
      run_type: "easy",
      run_time_period: "evening",
      rpe: 3,
      sleep_hours: 8,
      fatigue_level: 2,
      soreness_level: 2,
      avg_hr: null,
      max_hr: null,
      diet_preference: "normal",
      tomorrow_plan: "easy",
      symptoms: [],
    },
  },
  {
    id: "night-tempo",
    name: "高强度夜跑",
    summary: "8km tempo，RPE 8，明日强度冲突",
    payload: {
      distance_km: 8,
      duration_min: 48,
      run_type: "tempo",
      run_time_period: "night",
      rpe: 8,
      sleep_hours: 5.8,
      fatigue_level: 7,
      soreness_level: 5,
      avg_hr: 156,
      max_hr: null,
      diet_preference: "canteen",
      tomorrow_plan: "intensity",
      symptoms: [],
    },
  },
  {
    id: "long-high-rpe",
    name: "长距离高 RPE",
    summary: "16km long，RPE 9，酸痛偏高",
    payload: {
      distance_km: 16,
      duration_min: 105,
      run_type: "long",
      run_time_period: "morning",
      rpe: 9,
      sleep_hours: 5.8,
      fatigue_level: 8,
      soreness_level: 7,
      avg_hr: null,
      max_hr: null,
      diet_preference: "normal",
      tomorrow_plan: "long",
      symptoms: [],
    },
  },
];
